name: Build, Push, Deploy and Notify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t test_image .
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Push Docker image to Docker Hub
        run: docker push test_image

      - name: Notify on Slack - Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: 'success'
          text: 'Build, Push, and Deploy succeeded'
          fields: repo,message,commit,author,action,eventName,workflow,job,took
          author_name: 'GitHub Actions'

      - name: Notify on Slack - Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: 'failure'
          text: 'Build, Push, or Deploy failed'
          fields: repo,message,commit,author,action,eventName,workflow,job,took
          author_name: 'GitHub Actions'
