name: Build, Push, Deploy and Notify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t test_image .
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Push Docker image to Docker Hub
        run: docker push test_image

      - name: Notify on Slack - Success
        if: success()
        uses: slack/webhook-action@v2
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: '{"text": "Build, Push, and Deploy succeeded"}'

      - name: Notify on Slack - Failure
        if: failure()
        uses: slack/webhook-action@v2
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: '{"text": "Build, Push, or Deploy failed"}'
