name: 'Build, Push, Deploy and Notify'
'on':
  push:
    branches:
      - main
    env:
      SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notify slack on build start
        if: always()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: your-slack-channel
          status: STARTED
          color: good
      - name: Build Docker image
        run: docker build -t test_image .
      - name: Login to Docker Hub
        run: >-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{
          secrets.DOCKER_ACCESS_TOKEN }}
