name: Slack Notification

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack - Build Started
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          JOB_STATUS: ${{ job.status }}
          JOB_ID: ${{ github.run_id }}
        
 		
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
              "blocks": [
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "*Build Started*"
                      }
                  },
                  {
                      "type": "section",
                      "fields": [
                          {
                              "type": "mrkdwn",
                              "text": "*Status:*\n$JOB_STATUS"
                          },
                          {
                              "type": "mrkdwn",
                              "text": "*Job ID:*\n$JOB_ID"
                          }
                      ]
                  }
              ]
          }' "$SLACK_WEBHOOK_URL"
        
