name: Slack Notification

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack - Build Started
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
              "blocks": [
                  {
                      "type": "image",
                      "title": {
                          "type": "plain_text",
                          "text": "Build Started!"
                      },
                      "image_url": "https://media.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif",
                      "alt_text": "Build Started Animation"
                  }
              ]
          }' "$SLACK_WEBHOOK_URL"
